### PR TITLE
Fixes #10273 - Clone disk from template when preallocate marked

### PR DESCRIPTION
**Pull request by orrabin**
This won't work without a fix in fog.
The `attributes` here: https://github.com/fog/fog-core/blob/master/lib/fog/core/attributes.rb#L69 is not a `HashWithIndifferentAccess`.
As a result the options to use when building the vm: https://github.com/abenari/rbovirt/blob/master/lib/client/vm_api.rb#L58 will contain the keys `clone` and `disks` as strings which will prevent them from being part of the xml that is sent to ovirt: https://github.com/abenari/rbovirt/blob/master/lib/ovirt/vm.rb#L111-L117

### CODE REVIEW

**Comment by iNecas** [comment]
I'm not sure usage of HashWithIndifferentAccess will be accepted in fog-core, as it has no dependency on ActiveSupport now (probably on purpose).

Where is the place when the symbols that we use as keys become strings?

**Comment by orrabin** [comment]
For the record, the other way to avoid changing for-core as @iNecas suggested is adding `disks` and `clone` to the server attributes: https://github.com/fog/fog/blob/master/lib/fog/ovirt/models/compute/server.rb#L11
which would keep them as symbols while merging attributes and result in the correct xml in rbovirt.

**Comment by orrabin** [comment]
The fog pr has been merged so this can now be tested.

**Review by chris1984 — COMMENTED** [review]
@orrabin would a katello/foreman nightly be good for testing this pr?

**Comment by orrabin** [comment]
@chris1984 yes nightly is good. This needs to be tested with a compute resource for ovirt 3.6.

File: app/models/compute_resources/foreman/model/ovirt.rb [hunk 1]
```diff
@@ -210,10 +210,23 @@ def start_with_cloudinit(uuid, user_data = nil)
...
       end
+
+      change_allocation_volumes = args[:volumes_attributes].values.select{ |x| x[:preallocate] == '1' }
+      if args[:template].present? && change_allocation_volumes.present?
+        disks = []
+        change_allocation_volumes.each do |volume|
+          disks << {:id => volume[:id], :sparse => false, :format => 'raw' }
+        end
+
+        args.merge!(:clone => true, :disks => disks) unless disks.empty?
```
Comment (adamruzicka) [inline app/models/compute_resources/foreman/model/ovirt.rb]: Wouldn't it be cleaner if rewritten like this?
```ruby
if args[:template].present? && change_allocation_volumes.present?
  disks = change_allocation_volumes.map do |volume|
    { :id => volume[:id], :sparse => false, :format => 'raw' }
  end
  args.merge!(:clone => true, :disks => disks)
end
```

**Review by adamruzicka — APPROVED** [review]
Tested and it works flawlessly 👍 

Left one comment about possibility for refactoring.

**Comment by orrabin** [comment]
@adamruzicka thanks, I fixed your comment.
Edit: we need to find a new ovirt instance to retest, the one I was using seems to be broken now.

**Comment by iNecas** [comment]
Maybe time to revive this?

**Comment by raulbla** [comment]
it does not work with Ovirt 4.1. The api seems to accept clone=true only as a query string parameter to the post request creating the VM.

**Comment by orrabin** [comment]
@raulbla it doesn't work for nfs in 4.1, this is due to a change in ovirt (try it directly in ovirt - create a template and try to create a vm from it and you'll see it will stay on thin provisioning).
This can only be tested with block storage when testing with ovirt 4.1.

**Comment by raulbla** [comment]
@orrabin our environment is using block storage. however,  when we create a new vm from template using the gui and select the clone option it works correctly.

**Comment by pmoravec** [comment]
@orabin it fails also for iscsi / block-based data centers. clone=true argument didnt appear in the API call (patching both this and fog PR 3958).

File: app/models/compute_resources/foreman/model/ovirt.rb [hunk 2]
```diff
@@ -225,6 +230,16 @@ def create_vm(args = {})
       vm
     end
 
+    def preallocate_disks(args)
+      change_allocation_volumes = args[:volumes_attributes].values.select{ |x| x[:preallocate] == '1' }
```
Comment (pmoravec) [inline app/models/compute_resources/foreman/model/ovirt.rb:255]: If I am creating a VM without disks, `args[:volumes_attributes]` is empty (until I something overlooked) and this would raise `NoMethodError: undefined method `values' for nil:NilClass`, am I right?

Comment (orrabin) [reply app/models/compute_resources/foreman/model/ovirt.rb:255]: I added this if: https://github.com/theforeman/foreman/pull/4512/files#diff-20d0fb6f34ad993f1199e464ebe97df5R219 so this won't happen.

**Comment by orrabin** [comment]
Tested against 4.1 and to get it to work there I needed changes in rbovirt. I added: https://github.com/abenari/rbovirt/pull/122, once it's merged this can be tested again.

**Comment by orrabin** [comment]
Rebased, this still needs a new version of rbovirt to be tested.

**Comment by iNecas** [comment]
New version of rbovirt released. I guess it would be safest to also specify the version requirement on rbovirt here.

**Comment by shiramax** [comment]
Tested with Red Hat Virtualization Manager Version: 4.1.7.5-0.1.el7
and it worked for me.

**Review by iNecas — CHANGES_REQUESTED** [review]
Needs new fog-ovirt version and bump the dependency on it here. Will merge afterwards.

**Comment by orrabin** [comment]
@iNecas I updated the dependency and rebased.

**Review by iNecas — APPROVED** [review]

**Comment by iNecas** [comment]
Thanks @orrabin
