### PR TITLE
Fixes #22798 Include the vmFolder in the list_vms filter spec

### PR DESCRIPTION
**Pull request by agrare**
If a VM is in the root of the datacenter its parent is the vmFolder.
This folder was being skipped by the PropertyFilterSpec causing an
undefined method error '[]' for nil:NilClass when accessing the
vm['parent'] key.

git bisect points to e7e9821aa028957575a2aa0d79e696439f393e72 as introducing this issue.

Backtrace:
```
2018-03-06T11:11:34 fd0ae69d [app] [W] Error has occurred while listing VMs on dev-vc65 (VMware) | NoMethodError: undefined method `[]' for nil:NilClass
/home/agrare/src/foreman/app/services/fog_extensions/vsphere/mini_servers.rb:61:in `lookup_parent_folders'
/home/agrare/src/foreman/app/services/fog_extensions/vsphere/mini_servers.rb:62:in `lookup_parent_folders'
/home/agrare/src/foreman/app/services/fog_extensions/vsphere/mini_servers.rb:56:in `block in set_folder_paths'
/home/agrare/src/foreman/app/services/fog_extensions/vsphere/mini_servers.rb:55:in `each'
/home/agrare/src/foreman/app/services/fog_extensions/vsphere/mini_servers.rb:55:in `set_folder_paths'\
/home/agrare/src/foreman/app/services/fog_extensions/vsphere/mini_servers.rb:50:in `generate_folder_inventory'
/home/agrare/src/foreman/app/services/fog_extensions/vsphere/mini_servers.rb:21:in `all'
```

Which is failing on this line `attrs['path'] = folder_inventory[vm['parent']._ref][:path]` [[ref]](https://github.com/theforeman/foreman/blob/develop/app/services/fog_extensions/vsphere/mini_servers.rb#L29) because `folder_inventory` doesn't include the `datacenter.vmFolder`.

Before fix:
screenshot from 2018-03-06 11-32-32

After fix:
screenshot from 2018-03-06 11-55-55

Fixes #22798 - VMware: Exception listing VMs in the root of the datacenter

### CODE REVIEW

**Comment by agrare** [comment]
Hey @dLobatog not sure if you're the right person to review this but you looked at https://github.com/theforeman/foreman/pull/5171, could you take a look at this?

**Comment by ohadlevy** [comment]
@agrare welcome!
@timogoebel mind having a look?

**Comment by ohadlevy** [comment]
@agrare in your screenshots, I can see that folder has no value? I assume it should be ```/``` ?

**Comment by timogoebel** [comment]
@agrare: Thanks for the fix and welcome. Looks good to me. Can you please also take a look at @ohadlevy's comment?

**Comment by agrare** [comment]
> I can see that folder has no value? I assume it should be / ?

Before this change VMs in the root of the datacenter would have a blank folder property.

It looks like https://github.com/theforeman/foreman/commit/e7e9821aa028957575a2aa0d79e696439f393e72 also broke the MiniServer initializer by passing `attrs['path']` instead of `attrs[:path]` which was causing no folders to be shown, the most recent commit fixes this and this is the new screenshot

screenshot from 2018-03-12 09-21-08

**Comment by ohadlevy** [comment]
[ok to test]

**Comment by timogoebel** [comment]
~~@agrare: Thanks. I am testing this right now, but only get an empty vm list. I'll try to look into it further.~~

**Review by timogoebel — APPROVED** [review]
I take my last comment back, works very well. Thanks @agrare. Will merge pending Jenkins.

**Comment by agrare** [comment]
Thanks for the review @timogoebel !

**Comment by ohadlevy** [comment]
[test foreman]

**Comment by ohadlevy** [comment]
thanks @agrare!
