### PR TITLE
Fixes #7505 - Changed the way trends are stored in the DB. Now they are ...

### PR DESCRIPTION
**Pull request by ShimShtein**
...stored as intervals.
Added a new rake task trends:reduce that should reduce the number of trend points that are already stored in the DB.

### CODE REVIEW

File: db/migrate/20150202094307_add_range_to_trend_counters.rb [hunk 1]
```diff
@@ -0,0 +1,22 @@
+class AddRangeToTrendCounters < ActiveRecord::Migration
+  def change
+    add_column :trend_counters, :interval_start, :datetime
+    add_column :trend_counters, :interval_end, :datetime
```
Comment (ohadlevy) [inline db/migrate/20150202094307_add_range_to_trend_counters.rb:4]: indexes?

File: db/migrate/20150202094307_add_range_to_trend_counters.rb [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+
+    trend_lines = TrendCounter.order(:trend_id).group_by {|counter| counter.trend_id}
```
Comment (ohadlevy) [inline db/migrate/20150202094307_add_range_to_trend_counters.rb]: this could be a lot of records, maybe find_in_batches?

File: db/migrate/20150202094307_add_range_to_trend_counters.rb [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+
+    trend_lines.each do |trend_id, line|
+      sorted_counters = line.sort_by {|counter| counter.created_at}
+
+      first_record = sorted_counters.first
+      first_record.interval_start = first_record.created_at
+
+      sorted_counters.drop(1).each_with_index do |counter, idx|
```
Comment (ohadlevy) [inline db/migrate/20150202094307_add_range_to_trend_counters.rb]: why drop(1)?

File: db/migrate/20150202094307_add_range_to_trend_counters.rb [hunk 4]
```diff
@@ -0,0 +1,22 @@
+class AddRangeToTrendCounters < ActiveRecord::Migration
+  def change
+    add_column :trend_counters, :interval_start, :datetime
+    add_column :trend_counters, :interval_end, :datetime
+
+    trend_lines = TrendCounter.order(:trend_id).group_by {|counter| counter.trend_id}
+
+    trend_lines.each do |trend_id, line|
+      sorted_counters = line.sort_by {|counter| counter.created_at}
```
Comment (ohadlevy) [inline db/migrate/20150202094307_add_range_to_trend_counters.rb]: can you try this with a large dataset? something like 500k records or more?

File: lib/tasks/convert.rake [hunk 5]
```diff
@@ -96,7 +96,12 @@ namespace :db do
               when /^postgresql/
                 "ALTER TABLE #{table_name} DISABLE TRIGGER ALL;"
               end
-        DevelopmentModelClass.connection.execute(sql) if sql
+
+        begin
+          DevelopmentModelClass.connection.execute(sql) if sql
```
Comment (ohadlevy) [inline lib/tasks/convert.rake]: please dont include this change in this PR.

File: lib/tasks/trends.rake [hunk 6]
```diff
@@ -29,4 +29,63 @@ namespace :trends do
...
+
+      sorted_counters = line.sort_by {|counter| counter.created_at}
+
+      sorted_counters.drop(1).each_with_index do |counter, idx|
+        to_remove << counter unless TrendImporter.should_create_counter?(sorted_counters[idx], counter.count, counter.created_at)
+      end
+
+      TrendCounter.destroy(to_remove)
+
+      trend_line_count += 1
```
Comment (ohadlevy) [inline lib/tasks/trends.rake]: you can simply count the response from TtrendCounter.destroy

File: lib/tasks/trends.rake [hunk 7]
```diff
@@ -29,4 +29,63 @@ namespace :trends do
...
+      puts "Reduced trend id: #{trend_id}, #{trend_line_count} of #{trend_lines.count}"
+    end
+  end
+
+#  # Basic Ramer-Douglas-Peucker algorithm implementation.
+#  # see: http://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm
+#  # Reduces number of points in a single trend line without creating visible distortions.
```
Comment (ohadlevy) [inline lib/tasks/trends.rake]: maybe we can keep the credit, but not sure if we need the algorithm itself?

File: app/helpers/trends_helper.rb [hunk 8]
```diff
@@ -33,8 +33,15 @@ def chart_data(trend, from = Setting.max_trend, to = Time.zone.now)
     values = trend.values
     labels = {}
     values.includes(:trendable).each {|v| labels[v.id] = [v.to_label, trend_path(:id => v)]}
-    values.includes(:trend_counters).where(["trend_counters.created_at > ?", from]).reorder("trend_counters.created_at").each_with_index.map do |value, idx|
-      data =  value.trend_counters.map { |t|  [t.created_at.to_i*1000, t.count]  }
+    values.includes(:trend_counters).where(["trend_counters.interval_start > ? or trend_counters.interval_end > ? or trend_counters.interval_end is null", from, from]).reorder("trend_counters.interval_start").each_with_index.map do |value, idx|
```
Comment (ohadlevy) [inline app/helpers/trends_helper.rb]: is in on purpose that both interval_start and interval_end are bigger then "from" shouldnt it be one bigger and the other smaller then?

Comment (ohadlevy) [inline app/helpers/trends_helper.rb]: can you also cut down the line length? its a bit too long to read.

File: app/helpers/trends_helper.rb [hunk 9]
```diff
@@ -33,8 +33,15 @@ def chart_data(trend, from = Setting.max_trend, to = Time.zone.now)
...
+      data = []
+      value.trend_counters.each do |counter|
+        #cut the left side of the graph
+        interval_start = counter.interval_start > from ? counter.interval_start : from
+        next_timestamp = counter.try(:interval_end) || Time.now
```
Comment (ohadlevy) [inline app/helpers/trends_helper.rb:42]: why try? can a counter be nil?

Comment (ohadlevy) [inline app/helpers/trends_helper.rb:42]: also, wonder if we should always store time in UTC

File: app/helpers/trends_helper.rb [hunk 10]
```diff
@@ -33,8 +33,15 @@ def chart_data(trend, from = Setting.max_trend, to = Time.zone.now)
...
+        data << [interval_start.to_i*1000, counter.count]
+        data << [next_timestamp.to_i*1000, counter.count]
```
Comment (ohadlevy) [inline app/helpers/trends_helper.rb]: why *1000? is that the time interval?

Comment (ohadlevy) [inline app/helpers/trends_helper.rb]: ah nm, i see

File: app/services/trend_importer.rb [hunk 11]
```diff
@@ -32,17 +32,34 @@ def update_trend_counters
...
     Trend.has_value.each do |trend|
+      new_count = if trend.is_a? FactTrend
+                    counter_hash[trend.trendable_id][trend.fact_value]
+                  else
+                    counter_hash[trend.trendable_type][trend.trendable_id]
+                  end || 0
+
+      latest_counter = trend.trend_counters.order(:created_at).last
+      if latest_counter
+        latest_counter.interval_end = timestamp
```
Comment (ohadlevy) [inline app/services/trend_importer.rb:42]: if the latest counter has changed, should not we keep the value of the last time the count was measured ? changing it to the current timestamp is odd if the value already changed?

File: app/services/trend_importer.rb [hunk 12]
```diff
@@ -32,17 +32,34 @@ def update_trend_counters
...
+
       counter = trend.trend_counters.new
-      counter.count = if trend.is_a? FactTrend
-                        counter_hash[trend.trendable_id][trend.fact_value]
-                      else
-                        counter_hash[trend.trendable_type][trend.trendable_id]
-                      end || 0
+      counter.count = new_count
       counter.created_at = timestamp
+      counter.interval_start = timestamp
```
Comment (ohadlevy) [inline app/services/trend_importer.rb]: can probably do it in a oneliner:

``` ruby
trend.trend_counters.create! :count => new_count, :created_at => timestamp, :interval_start => timestamp ...
```

File: db/migrate/20150202094307_add_range_to_trend_counters.rb (hunk 1 above)
Comment (ShimShtein) [inline db/migrate/20150202094307_add_range_to_trend_counters.rb:4]: Number of records that are fetched should be relatively small, it shouldn't cross 1000 records. I don't think it justifies an index

File: db/migrate/20150202094307_add_range_to_trend_counters.rb (hunk 3 above)
Comment (ShimShtein) [inline db/migrate/20150202094307_add_range_to_trend_counters.rb]: The proper word would be skip. It sets the `#end_interval` of the previous counter to the start of the next one: `a[i].end = a[i+1].start`. I am updating `sorted_counters` (unshifted) with values from `#each_with_index` (shifted)

File: lib/tasks/trends.rake (hunk 6 above)
Comment (ShimShtein) [inline lib/tasks/trends.rake]: I am counting the number of groups (trend lines), and the `#destroy` will return the number of removed data points.

File: lib/tasks/trends.rake (hunk 7 above)
Comment (ShimShtein) [inline lib/tasks/trends.rake]: The algorithm is already written, it's kind of a shame to throw it away. For now we don't need it - we are using a simple interval based mechanism, but the algo can be enabled in the `:reduce` rake task instead of the `each_with_index` loop

File: app/helpers/trends_helper.rb (hunk 8 above)
Comment (ShimShtein) [inline app/helpers/trends_helper.rb]: It is on purpose, I should take all intervals that begin or end **after** the beginning of the viewed region ("from").
Actually the condition on `interval_start` is redundant - every interval that begins after "from" will either end after it or will have its `interval_end` set to `NULL`.
I will remove the redundant condition, and reformat the line.

File: app/helpers/trends_helper.rb (hunk 9 above)
Comment (ShimShtein) [inline app/helpers/trends_helper.rb:42]: Interval end can be `NULL`, if the interval has not been ended yet.
The timestamp is stored as `timestamp without time zone` (at least in pgsql), and rails puts there the UTC value as far as I have checked, so it should be OK with timezones.

File: app/services/trend_importer.rb (hunk 11 above)
Comment (ShimShtein) [inline app/services/trend_importer.rb:42]: Last measurement value is stored in `update_date` of the latest counter. If the value is changed, that means that we need to end the latest stored counter (set its `interval_end`), and begin a new interval. It is performed after the `next unless...` line.

File: db/migrate/20150202094307_add_range_to_trend_counters.rb (hunk 2 above)
Comment (ShimShtein) [inline db/migrate/20150202094307_add_range_to_trend_counters.rb]: At this point there shouldn't be too much records, but I will ensure it by running the `rake trends:reduce` task as a part of the migration process.
This task is idempotent, so there is no problem running it even if it was executed manually before running the migration.

File: db/migrate/20150202094307_add_range_to_trend_counters.rb (hunk 4 above)
Comment (ShimShtein) [inline db/migrate/20150202094307_add_range_to_trend_counters.rb]: I'm working with 1.5M records of trend counters

**Comment by ohadlevy** [comment]
when trying to migrate on my old database I get:

```
undefined method `to_sym' for 0:Fixnum/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/sanitization.rb:60:in `block in expand_hash_conditions_for_aggregates'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/sanitization.rb:59:in `each'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/sanitization.rb:59:in `expand_hash_conditions_for_aggregates'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/relation/query_methods.rb:326:in `build_where'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/relation/query_methods.rb:136:in `where'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/querying.rb:9:in `where'
/home/ohad/git/foreman/lib/tasks/trends.rake:40:in `block (3 levels) in <top (required)>'
/home/ohad/git/foreman/lib/tasks/trends.rake:39:in `each'
/home/ohad/git/foreman/lib/tasks/trends.rake:39:in `each_with_index'
/home/ohad/git/foreman/lib/tasks/trends.rake:39:in `block (2 levels) in <top (required)>'
/home/ohad/git/foreman/db/migrate/20150202094307_add_range_to_trend_counters.rb:6:in `change'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:407:in `block (2 levels) in migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:407:in `block in migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:389:in `migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:528:in `migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:775:in `call'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:775:in `block in ddl_transaction'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:775:in `ddl_transaction'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:719:in `block in migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:700:in `each'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:700:in `migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:570:in `up'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:551:in `migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `to_sym' for 0:Fixnum
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/sanitization.rb:60:in `block in expand_hash_conditions_for_aggregates'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/sanitization.rb:59:in `each'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/sanitization.rb:59:in `expand_hash_conditions_for_aggregates'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/relation/query_methods.rb:326:in `build_where'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/relation/query_methods.rb:136:in `where'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/querying.rb:9:in `where'
/home/ohad/git/foreman/lib/tasks/trends.rake:40:in `block (3 levels) in <top (required)>'
/home/ohad/git/foreman/lib/tasks/trends.rake:39:in `each'
/home/ohad/git/foreman/lib/tasks/trends.rake:39:in `each_with_index'
/home/ohad/git/foreman/lib/tasks/trends.rake:39:in `block (2 levels) in <top (required)>'
/home/ohad/git/foreman/db/migrate/20150202094307_add_range_to_trend_counters.rb:6:in `change'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:407:in `block (2 levels) in migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:407:in `block in migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:389:in `migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:528:in `migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:775:in `call'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:775:in `block in ddl_transaction'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:775:in `ddl_transaction'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:719:in `block in migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:700:in `each'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:700:in `migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:570:in `up'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/migration.rb:551:in `migrate'
/home/ohad/.rvm/gems/ruby-2.1.5@foreman/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
```

File: lib/tasks/trends.rake [hunk 13]
```diff
@@ -29,4 +29,57 @@ namespace :trends do
     end
   end
 
+  desc 'Reduces amount of points for each trend group for the last month'
+  task :reduce => :environment do
+    #get the records that sould remain in the DB - should'n be too much of them
+    change_points = ActiveRecord::Base.connection.execute("select trend_id, trend_counters.count, min(created_at) as created_at from trend_counters group by trend_id, count")
```
Comment (ohadlevy) [inline lib/tasks/trends.rake]: consider using to avoid adapter specific issues

``` ruby
TrendCounter.select("trend_id, trend_counters.count, min(created_at) AS created_at").group("trend_id, count")
```

File: lib/tasks/trends.rake [hunk 14]
```diff
@@ -29,4 +29,57 @@ namespace :trends do
     end
   end
 
+  desc 'Reduces amount of points for each trend group for the last month'
+  task :reduce => :environment do
+    #get the records that sould remain in the DB - should'n be too much of them
+    change_points = TrendCounter.unscoped.select("trend_id, trend_counters.count, min(created_at) as created_at").group("trend_id, count")
```
Comment (ohadlevy) [inline lib/tasks/trends.rake]: this actually misses a few points, as it will care for all counters with the same value regardless of trend,e.g.

`___|---|___` kind of graph will count both values from left and right incorrectly.

IMHO you should use something like (pseudo code)
for each trend, find the starting point, then search for the first trend that has a different counter.
once you find that, mark the start and end dates, create a new counter entry.
delete all of the trend counters in the range you just found
loop until you there are no more trend counters.

File: lib/tasks/trends.rake [hunk 15]
```diff
@@ -29,4 +29,102 @@ namespace :trends do
...
+    start = Time.now
+
+    trends = Trend.pluck(:id)
+    trends_count = trends.length
+    current_record = 0
+
+    trends.each do |trend_id|
+      puts "Working on trend_id #{trend_id}, #{(current_record += 1)} of #{trends_count}"
+
+      current_interval = TrendCounter.where(trend_id: trend_id).order(:created_at).first
```
Comment (ohadlevy) [inline lib/tasks/trends.rake:42]: should we add that also interval_end and interval_start are nil?

File: lib/tasks/trends.rake [hunk 16]
```diff
@@ -29,4 +29,102 @@ namespace :trends do
...
+      end
+      current_interval.save!
+    end
+
+    TrendCounter.unscoped.where(interval_start: nil).delete_all
+
+    puts "It took #{Time.now - start} seconds to complete"
+  end
+
+  task :reduce_batches => :environment do
```
Comment (ohadlevy) [inline lib/tasks/trends.rake]: is this an unused task?

File: lib/tasks/trends.rake (hunk 15 above)
Comment (ShimShtein) [inline lib/tasks/trends.rake:42]: No need, the current version of the task is idempotent - you can run it more than once. It won't ruin the data.

Comment (ohadlevy) [inline lib/tasks/trends.rake:42]: right, but its useless in this case?

File: lib/tasks/trends.rake (hunk 16 above)
Comment (ShimShtein) [inline lib/tasks/trends.rake]: It's an alternative way of doing the same job. If the data is not suitable for the chatty way (as in trends:reduce) the user can run this version manually, and fix the DB.

File: lib/tasks/trends.rake (hunk 15 above)
Comment (ShimShtein) [inline lib/tasks/trends.rake:42]: Pretty much - it won't change a thing, unless there are intervals that can be consolidated. There shouldn't be in the common use case, but if there will be - they would be consolidated.

**Comment by dLobatog** [comment]
[test] because of the latest enabled cops

**Comment by ohadlevy** [comment]
@ShimShtein can you rebase please?

**Comment by ShimShtein** [comment]
@ohadlevy, Rebased and cleaned, ready for merging :)

**Comment by ohadlevy** [comment]
@ShimShtein looks good, missing tests :)

File: app/helpers/trends_helper.rb [hunk 17]
```diff
@@ -32,8 +32,18 @@ def chart_data(trend, from = Setting.max_trend, to = Time.zone.now)
...
-    values.includes(:trend_counters).where(["trend_counters.created_at > ?", from]).reorder("trend_counters.created_at").each_with_index.map do |value, idx|
-      data =  value.trend_counters.map { |t|  [t.created_at.to_i*1000, t.count]  }
+    values.includes(:trend_counters).where(["trend_counters.interval_end > ? or trend_counters.interval_end is null", from])
+                                    .reorder("trend_counters.interval_start")
+                                    .each_with_index.map do |value, idx|
+      data = []
+      value.trend_counters.each do |counter|
+        #cut the left side of the graph
+        interval_start = (counter.interval_start || from) > from ? counter.interval_start : from
+        next_timestamp = counter.try(:interval_end) || Time.now
```
Comment (ohadlevy) [inline app/helpers/trends_helper.rb:42]: would you reduce this by a ms, so the graph wont append one on the other?

**Comment by ohadlevy** [comment]
merged as 8e567e2 thanks @ShimShtein!
