### PR TITLE
fixes #26528 - graphql: refactor AuthorizedModelQuery to resolver

### PR DESCRIPTION
**Pull request by timogoebel**
This is a follow-up PR of #6633. It refactors the `AuthorizedModelQuery` object into a resolver.

It also fixes quite a few small glitches I found regarding sorting, that's why this would be great to have in 1.22 (@tbrisker, @xprazak2).

It also adds filtering by specific taxonomies so you can do queries like: Graphql, please give me all subnets that are in the Unicorn location.

```graphql
query {
  subnets(location: "Unicorn") {
    nodes {
      name
    }
  }
}
```

Don't be alarmed by all the changes. I had to change the tests from `class Queries::AbcTest` to `module Queries; class AbcTest` or tests would not pass. Just look at the first three and last file.

Pro Tipp: Github has a feature that allows you hide all whitespace changes from a diff:

image

### CODE REVIEW

File: app/graphql/resolvers/concerns/collection.rb [hunk 1]
```diff
@@ -7,21 +7,126 @@ module Collection
...
+        _, type_name, id = Foreman::GlobalId.decode(global_id)
+
+        raise GraphQL::ExecutionError.new(message: "Global ID for #{taxonomy_name} filter is for other graphql type (expected '#{taxonomy_name}', got '#{type_name}')") unless taxonomy_name == type_name
+
+        id.to_i
+      end
+
+      def resolve_taxonomy_name_to_id(taxonomy_class, taxonomy_name)
+        id = taxonomy_class.find_by(name: taxonomy_name)
+        raise GraphQL::ExecutionError.new(message: "#{taxonomy_class.name} could not be found my name #{name}.") unless id
```
Comment (tbrisker) [inline app/graphql/resolvers/concerns/collection.rb]:
```suggestion
        raise GraphQL::ExecutionError.new("#{taxonomy_class.name} could not be found by name #{taxonomy_name}.") unless id
```

File: app/graphql/resolvers/concerns/collection.rb [hunk 2]
```diff
@@ -7,21 +7,126 @@ module Collection
...
+        elsif organization.present?
+          taxonomy_ids << resolve_taxonomy_name_to_id(Organization, organization)
+        end
+
+        taxonomy_ids.uniq
+      end
+
+      def resolve_taxonomy_global_id(taxonomy_class, global_id)
+        taxonomy_name = taxonomy_class.name
+        _, type_name, id = Foreman::GlobalId.decode(global_id)
```
Comment (tbrisker) [inline app/graphql/resolvers/concerns/collection.rb:113]: This could be confusing for users (such as myself) used to filtering by non-global taxonomy ids. It also fails with a fun error `undefined method 'split' for nil:NilClass` when you pass a number - could we perhaps detect if it is a number or not and by that deduce if it's a global id or an object id?

File: app/graphql/resolvers/concerns/collection.rb [hunk 3]
```diff
@@ -7,21 +7,126 @@ module Collection
...
+
+        raise GraphQL::ExecutionError.new(message: "Global ID for #{taxonomy_name} filter is for other graphql type (expected '#{taxonomy_name}', got '#{type_name}')") unless taxonomy_name == type_name
```
Comment (tbrisker) [inline app/graphql/resolvers/concerns/collection.rb]:
```suggestion
        raise GraphQL::ExecutionError.new("Global ID for #{taxonomy_name} filter is for other graphql type (expected '#{taxonomy_name}', got '#{type_name}')") unless taxonomy_name == type_name
```

File: app/graphql/resolvers/concerns/collection.rb [hunk 4]
```diff
@@ -7,21 +7,126 @@ module Collection
...
+
+        filters
+      end
+
+      def search_and_sort_filter(search:, sort_by:, sort_direction:)
+        lambda do |scope|
+          begin
+            scope.search_for(*search_options(search: search, sort_by: sort_by, sort_direction: sort_direction))
+          rescue ScopedSearch::QueryNotSupported => error
+            raise GraphQL::ExecutionError.new(message: error.message)
```
Comment (tbrisker) [inline app/graphql/resolvers/concerns/collection.rb]:
```suggestion
            raise GraphQL::ExecutionError.new(error.message)
```

File: app/graphql/resolvers/concerns/collection.rb [hunk 5]
```diff
@@ -7,21 +7,126 @@ module Collection
...
-      def resolve(search: nil, order: nil, order_by: nil)
-        params = {
-          order_by: order_by,
-          order: order,
-          search: search
-        }
+      def taxonomy_id_filter(taxonomy_ids)
+        lambda do |scope|
+          scope.joins(:taxable_taxonomies)
+            .where(taxable_taxonomies: {taxonomy_id: taxonomy_ids}).distinct
```
Comment (tbrisker) [inline app/graphql/resolvers/concerns/collection.rb:88]: Perhaps this should use one of the methods in Taxonomix, such as `scope_by_taxable_ids`?

File: app/graphql/resolvers/concerns/collection.rb [hunk 6]
```diff
@@ -7,21 +7,126 @@ module Collection
...
+      end
+
+      def authorized_scope
+        return model_class unless model_class.respond_to?(:authorized)
+
+        permission = model_class.find_permission_name(:view)
+        model_class.authorized_as(user, permission, model_class)
+      end
+
+      def search_options(search:, sort_by:, sort_direction:)
```
Comment (tbrisker) [inline app/graphql/resolvers/concerns/collection.rb:47]: I wonder, could we perhaps reuse some logic from the api base controllers here?

**Review by tbrisker — CHANGES_REQUESTED** [review]
See inline.
Also something to consider, perhaps in a separate PR - the taxonomy filter isn't applied to nested objects. e.g., if do a query like:
```graphql
{
  domains(location: "TLV") {
    nodes {
      name
      subnets(type: "Subnet::Ipv4") {
        nodes {
          name
          id
        }
      }
    }
  }
}
```
I will only get the domains in the TLV location, but I will get all of their subnets, not just the ones in TLV.

File: app/graphql/resolvers/concerns/collection.rb (hunk 6 above)
Comment (timogoebel) [reply app/graphql/resolvers/concerns/collection.rb:47]: We just have this line that we could reuse. I think it's not worth sharing. But if you insist, I'll extract this some kind of shared concern.
https://github.com/theforeman/foreman/blob/7500537eefac12d1e58daa58c1efd346c6dc719c/app/controllers/api/base_controller.rb#L216-L218

File: app/graphql/resolvers/concerns/collection.rb (hunk 2 above)
Comment (timogoebel) [reply app/graphql/resolvers/concerns/collection.rb:113]: I'm reluctant on allowing users to pass a rails id. Graphql should only use global IDs. If we make exceptions to this rule, it'll get even more confusing in the long term. I'll add better error handling though.

File: app/graphql/resolvers/concerns/collection.rb (hunk 5 above)
Comment (timogoebel) [reply app/graphql/resolvers/concerns/collection.rb:88]: I believe the name of `scope_by_taxable_ids` is misleading. It's used to apply a filter on the actual resource (and not join the resource with the taxonomy table and filter the taxonomies by the given ids).
I haven't found another suitable method, though. We could add a method to `Taxonomix`, but I'm not sure if that'll lead to cleaner code.

File: app/graphql/resolvers/concerns/collection.rb (hunk 6 above)
Comment (tbrisker) [reply app/graphql/resolvers/concerns/collection.rb:47]: i don't insist, just wondering because we have quite similar logic for search filtering in the api and wanted to avoid duplication if it makes sense.

**Comment by timogoebel** [comment]
@tbrisker: Thanks for your comments. I believe I addressed all of them.

File: app/graphql/resolvers/concerns/collection.rb (hunk 5 above)
Comment (tbrisker) [reply app/graphql/resolvers/concerns/collection.rb:88]: Taxonomix could definitely be improved :) I think that might be because this join could be very painful on large tables as taxable_taxonomies is usually huge.

File: app/services/foreman/global_id.rb [hunk 7]
```diff
@@ -16,14 +17,27 @@ def self.encode(type_name, object_value, version: DEFAULT_VERSION)
...
+      raise InvalidGlobalIdException unless type_name.present? && object_value.present?
       [version.to_i, type_name, object_value]
     end
 
     def self.for(obj)
       encode(obj.class.name, obj.id)
     end
+
+    def self.base64_encoded?(string)
+      !!string.match(BASE64_FORMAT)
```
Comment (tbrisker) [inline app/services/foreman/global_id.rb:34]:
```suggestion
      string.match?(BASE64_FORMAT)
```

Comment (timogoebel) [reply app/services/foreman/global_id.rb:34]: Done.

Comment (timogoebel) [reply app/services/foreman/global_id.rb:34]: This does not work on ruby 2.3. The tests fail because of a `undefined method 'match?'`.

**Review by tbrisker — APPROVED** [review]
Thanks @timogoebel ! I think we could improve taxonomix to make this simpler, but I'm fine with iterating on it in the future.
