### PR TITLE
Fixes #26871 - restore taxonomy name as ID in API

### PR DESCRIPTION
**Pull request by ares**
This used to work a long time ago
```
url -u admin:changeme  --header "Content-Type:application/json" "https://foreman.example.tst/api/v2/organizations/Ares/parameters/"
```

but now returns 404 and only ID of organization can be used

Prerequisites for testing:
* have at least one org or loc

Tests needed (anticipated impacts):
* perform the API call and see you get reasonable response for existing org/loc
* check that regular work with API using taxonomies work

### CODE REVIEW

File: app/controllers/concerns/application_shared.rb [hunk 1]
```diff
@@ -33,7 +33,7 @@ def set_taxonomy
           if params["#{taxonomy}_id"].blank? # the key is present and explicitly set to nil which indicates "any" context
             determined_taxonomy = nil
           else
-            determined_taxonomy = available.where(:id => params["#{taxonomy}_id"]).first
+            determined_taxonomy = available.friendly.find(params["#{taxonomy}_id"])
```
Comment (tbrisker) [inline app/controllers/concerns/application_shared.rb]: this will raise `ActiveRecord::RecordNotFound` if it isn't found instead of returning `nil`

Comment (ares) [reply app/controllers/concerns/application_shared.rb]: good point, restored the behavior via rescue, IIRC using `friendly` required to use find

**Review by tbrisker — APPROVED** [review]
LGTM, pushed rebase to make sure tests pass.

**Review by tbrisker — CHANGES_REQUESTED** [review]
sadly test failures are related :crying_cat_face:

File: app/controllers/concerns/application_shared.rb [hunk 2]
```diff
@@ -33,7 +33,9 @@ def set_taxonomy
           if params["#{taxonomy}_id"].blank? # the key is present and explicitly set to nil which indicates "any" context
             determined_taxonomy = nil
           else
-            determined_taxonomy = available.where(:id => params["#{taxonomy}_id"]).first
+            identifier = params["#{taxonomy}_id"]
+            determined_taxonomy = available.friendly.find(identifier) rescue ActiveRecord::RecordNotFound
+            determined_taxonomy ||= available.where(:id => identifier).first
```
Comment (ares) [inline app/controllers/concerns/application_shared.rb]: the tests (or at least some) were failing because the new didn't address the case, where id was in for of "123-name", rails auto converts that to 123, since id is integer. Friendly find does not work with it. So we fallback to old way if friendly id didn't find anything.

Comment (tbrisker) [reply app/controllers/concerns/application_shared.rb]: shouldn't we fix the incorrect tests instead?

Comment (ares) [reply app/controllers/concerns/application_shared.rb]: well, but 123-name is generally accepted id form too, or am I missing something?

Comment (tbrisker) [reply app/controllers/concerns/application_shared.rb]: Only where we use [`Parameterizable::ByIdName`](https://github.com/theforeman/foreman/blob/develop/app/models/concerns/parameterizable.rb#L20) (and taxonomies friendly id is by title).
tbh, we're quite inconsistent about these - some places use friendly, some places use parameterizable, some both or none, and each has several variants.

Comment (tbrisker) [reply app/controllers/concerns/application_shared.rb]: or actually, we do include that in taxonomies as well. interesting...

**Comment by ares** [comment]
[test foreman][test katello]

**Comment by tbrisker** [comment]
I think test failures are related (and also need a rebase)

**Comment by tbrisker** [comment]
test failures seem related.

File: app/controllers/concerns/application_shared.rb (hunk 2 above)
Comment (tbrisker) [reply app/controllers/concerns/application_shared.rb]: this could probably be resolved properly by using the `scope_by_resource_id` method introduced by https://github.com/theforeman/foreman/pull/7289/

Comment (ares) [reply app/controllers/concerns/application_shared.rb]: testing that, let's see if that makes tests happy

**Comment by ares** [comment]
Failures are unrelated now

**Comment by mmoll** [comment]
> Failures are unrelated now

Sure? :) 

```
NoMethodError: undefined method `scope_by_resource_id' for #<HostsController:0x00007fa14b0afc50>...
```

**Comment by ares** [comment]
Not anymore :-) however it's weird since it's only hostjs tests, that are known to be intermittent. I'll see if I can reproduce locally and debug, what's going on. Perhaps the controller does not include the concern or inherit from the common parent.

**Comment by tbrisker** [comment]
[test foreman]

**Comment by tbrisker** [comment]
test failures are consistent

**Comment by ares** [comment]
The error is odd, this lives in shared concern that is included in `ApplicationController`, I didn't find any magic in this test. Running again to see, if it's all the time the same 3 tests.

```
HostJSTest::NIC modal window::adding interfaces.test_0005_selecting domain updates puppetclass parameters
HostJSTest::create new host page.test_0005_sets fields to "inherit" when hostgroup is selected
HostJSTest::create new host page.test_0004_saves correct values for inherited fields without hostgroup
```

**Comment by ares** [comment]
[test foreman]

**Comment by tbrisker** [comment]
What's the status here @ares ?

**Comment by ares** [comment]
I have no idea why these fail :-( I spent time on these, but can't reproduce locally, not sure when I'll have time again to fix tests

**Comment by tbrisker** [comment]
considering the taxonomy names as id have been unsupported for two years at least, should we maybe leave it like that and close this pr?

**Comment by tbrisker** [comment]
Ping @ares , any objections to closing this?

**Comment by ezr-ondrej** [comment]
[test foreman]

**Comment by ares** [comment]
Rebasing just to be sure, however I'm not against closing. It is a valid bug though.

File: app/controllers/concerns/application_shared.rb [hunk 3]
```diff
@@ -33,7 +33,7 @@ def set_taxonomy
           if params["#{taxonomy}_id"].blank? # the key is present and explicitly set to nil which indicates "any" context
             determined_taxonomy = nil
           else
-            determined_taxonomy = available.where(:id => params["#{taxonomy}_id"]).first
+            determined_taxonomy = scope_by_resource_id(available, params["#{taxonomy}_id"]).first
```
Comment (ezr-ondrej) [inline app/controllers/concerns/application_shared.rb:36]: This method is defined in `Api::BaseController` you can't use it in `ApplicationShared` as it is included in both UI and API controllers.
Why it did not fail locally, I've got no clue, but it should fail

**Comment by tbrisker** [comment]
[test katello]

**Comment by tbrisker** [comment]
[test katello]

**Review by tbrisker — APPROVED** [review]
Good find @ezr-ondrej and thanks @ares for pushing this through for a year and half!
